[tool.poetry]
name = "ai-service"
version = "0.1.0"
description = "AI-powered documentation Q&A service using RAG"
authors = ["VitePress-Lite Team"]
readme = "README.md"
packages = [{include = "ai_service"}]

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.104.1"
uvicorn = {extras = ["standard"], version = "^0.24.0.post1"}
pydantic = "^2.5.0"
pydantic-settings = "^2.2.1"
chromadb = "^0.4.24"
sentence-transformers = "^2.7.0"
openai = "^1.12.0"
httpx = "^0.26.0"
loguru = "^0.7.2"
markdown = "^3.5.2"
beautifulsoup4 = "^4.12.3"
numpy = "^1.24.3"
python-dotenv = "^1.0.1"
orjson = "^3.9.15"
packaging = "^24.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.3"
pytest-asyncio = "^0.23.2"
black = "^23.12.0"
isort = "^5.13.2"
flake8 = "^6.1.0"
mypy = "^1.8.0"
httpx = "^0.26.0"
deptry = "^0.23.1"
torch = "2.2.2"
pytest-cov = "^5.0.0"
aiohttp = "^3.12.15"

[tool.poetry.scripts]
ai-service = "ai_service.__main__:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 88
target-version = ['py310']
include = '\.pyi?$'
extend-exclude = '''
/(
  \.git
  | \.venv
  | build
  | dist
)/
'''

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 88

[tool.mypy]
python_version = "3.10"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true 
